type: wordpress
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
mutagen_enabled: true
router_http_port: "80"
router_https_port: "443"

hooks:
  pre-stop:
    - host_exec: bash -lc 'mkdir -p .ddev/backups && ddev export-db --file=.ddev/backups/auto-$(date +%F-%H%M).sql.gz'
  pre-delete:
    - host_exec: bash -lc 'mkdir -p .ddev/backups && ddev export-db --file=.ddev/backups/pre-delete-$(date +%F-%H%M).sql.gz'

